DROP TABLE item IF EXISTS;

CREATE TABLE item (
    item_id BIGINT generated by default as identity,
    price BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY  KEY(item_id)
);

DROP TABLE member IF EXISTS;

CREATE TABLE member (
    member_id BIGINT generated by default as identity,
    address VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY  KEY(member_id)
);

DROP TABLE orders IF EXISTS;

CREATE TABLE orders (
    order_id BIGINT generated by default as identity,
    qty BIGINT NOT NULL,
    total_price BIGINT NOT NULL,
    member_id BIGINT,
    item_id BIGINT,
    FOREIGN KEY(member_id) REFERENCES member,
    FOREIGN KEY(item_id) REFERENCES  item,
    PRIMARY  KEY(order_id)
);